Add mysql-shell python dependencies
canonical/mysql-container pull request #30
Opened 2023-06-20 17:53 UTC by carlcsaposs-canonical

`certifi` and `yaml` were added to the mysql-shell PPA but are not present in the rock

2023-06-20 19:35 UTC, shayancanonical approved these changes

2023-06-21 12:02 UTC, taurus-forever requested changes
I would say, not necessary, run-dependency added in pp3:
[mysql-shell - 8.0.33-0ubuntu0.22.04.1~ppa3](https://launchpad.net/~data-platform/+archive/ubuntu/mysql-shell/+sourcepub/14969918/+listing-archive-extra)

2023-06-21 13:03 UTC, carlcsaposs-canonical commented
@taurus-forever I re-built the snap and then the rock, and the apt packages are still missing from the rock

~~Looks like the PPA is still building~~ PPA finished building, re-built snap & rock—packages are still missing from rock

2023-06-22 20:22 UTC, paulomach commented
> @taurus-forever I re-built the snap and then the rock, and the apt packages are still missing from the rock
> 
> ~Looks like the PPA is still building~ PPA finished building, re-built snap & rock—packages are still missing from rock

That's strange - dependency looks correct on the ppa, but deb control without dependency versions:
```
Depends: libantlr4-runtime4.10.1 (>= 4.10.1+dfsg), ... , python3-certifi, python3-yaml
```
Not sure that's causing it though since it's a valid syntax. Check with Lena?

2023-06-23 18:55 UTC, carlcsaposs-canonical commented
asked in rockcraft channel: https://chat.charmhub.io/charmhub/pl/swy5idz8hbdt9qj559u5xbjt8w

2023-06-26 09:16 UTC, taurus-forever approved these changes
OK. LGTM to unblock you until rockcraft team is brewing the answer.
We can clean the explicit dependency later after the clarification.

2023-06-26 12:18 UTC, merged